steps:
  # 1. בנייה
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/calcium-spanner-449711-u1/mipo-backend/api:$SHORT_SHA
      - -t
      - europe-west1-docker.pkg.dev/calcium-spanner-449711-u1/mipo-backend/api:latest
      - .

  # 2. דחיפה ל-Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - --all-tags
      - europe-west1-docker.pkg.dev/calcium-spanner-449711-u1/mipo-backend/api

images:
  - europe-west1-docker.pkg.dev/calcium-spanner-449711-u1/mipo-backend/api:$SHORT_SHA
  - europe-west1-docker.pkg.dev/calcium-spanner-449711-u1/mipo-backend/api:latest

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 600s
